name: ci

on:
  push:
  pull_request:

jobs:
  ci:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Validate
        run: |
          brew tap sudosubin/check-jsonschema .
          brew install check-jsonschema
